addons: {}
after_failure:
- find . -name "TestSuite.txt" | xargs cat
after_success:
- export JAVA_TOOL_OPTIONS=-javaagent:$DFB_PROJECT_DIR/jacoco-agent-jdk8.jar=destfile=$DFB_PROJECT_DIR/jacoco.exec
- mvn test -Djacoco.skip=true -Dcobertura.skip=true -Dmaven.clover.skip=true test-compile
  failsafe:integration-test failsafe:verify -Dgpg.skip=true -Dgalen.use.fail.exit.code=false
- ./df-build.sh
- env > env.file
- curl -sL https://raw.githubusercontent.com/travis-ci/artifacts/master/install |
  bash
- artifacts upload --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY --bucket
  $DFB_AWS_BUCKET --target-paths $DFB_AWS_BUILD_PATH $(git ls-files -oi -x *.exec)
- artifacts upload --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY --bucket
  $DFB_AWS_BUCKET --target-paths $DFB_AWS_BUILD_PATH ${DFB_PROJECT_DIR}/env.file
before_install:
- /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile
  --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16
- wget -O beforebuild.sh $DFB_AGENTS_URL/beforebuild.sh
- chmod a+x beforebuild.sh
- ./beforebuild.sh
env:
  global:
  - DFB_PROJECT_DIR=$(pwd)
  - TMP_PROJECT_PARENT_DIR=$(dirname $DFB_PROJECT_DIR)
  - DFB_BUILD_ID=$TRAVIS_BUILD_ID
  - DFB_PRODUCT_NAME=$(basename $DFB_PROJECT_DIR)
  - DFB_OWNER_NAME=$(basename $TMP_PROJECT_PARENT_DIR)
  - DFB_PRODUCT_KEY=${DFB_OWNER_NAME}_${DFB_PRODUCT_NAME}
  - DFB_AWS_BUCKET=aline-external-ci-artifacts
  - DFB_AGENTS_URL=https://s3.amazonaws.com/${DFB_AWS_BUCKET}/agents
  - DFB_PACKAGING_URL=s3://${DFB_AWS_BUCKET}/artifacts/travis/
  - DFB_AWS_BUILD_PATH=/artifacts/travis/${DFB_PRODUCT_KEY}/${DFB_BUILD_ID}/output/
  - AWS_ACCESS_KEY_ID=AKIAIIU2LBOCCKXAIFZQ
  - AWS_SECRET_ACCESS_KEY=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
  - DFB_JTO=-javaagent:${DFB_PROJECT_DIR}/dfbuild-agent.jar=PACKAGING_BASE_URI=$DFB_PACKAGING_URL,PRODUCT_KEY=$DFB_PRODUCT_KEY/,BUILD_KEY=$DFB_BUILD_ID/,MODULES_KEY=modules/,START_TIME=0,BUILD_BASE_DIR=$DFB_PROJECT_DIR
  matrix:
  - DISPLAY=:99
install: 'true'
jdk:
- oraclejdk8
language: java
notifications: {}
script:
- export JAVA_TOOL_OPTIONS=$DFB_JTO
- mvn -Djacoco.skip=true -Dcobertura.skip=true -Dmaven.clover.skip=true clean test
  -Dgpg.skip=true -Dgalen.use.fail.exit.code=false
- mvn -Djacoco.skip=true -Dcobertura.skip=true -Dmaven.clover.skip=true test-compile
  failsafe:integration-test failsafe:verify -Dgpg.skip=true -Dgalen.use.fail.exit.code=false
# Modified by IntegrationTestInstrumentation at 2016-05-14 00:05:01.372844
